### ISSUE TITLE
Add a fix config by wrapping grunt-stylefmt

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/grunt-stylelint#8]

**Comment by radum** [comment]
What do you mean by fix config? Like a predefined one to run? Embedded in this module?

If so you want to move stylelint to peerdeps? Or...?

**Comment by jdforrester** [comment]
Sorry, this was mostly a note to myself. :-)

Some coding standards/style linters, like jscs and phpcs, will automatically fix issues they find if passed `fix: true`; this is very helpful, especially for adding new rules to large code bases. This is provided in stylelint via stylefmt but we don't yet expose it.

**Comment by jeddy3** [comment]
> This is provided in stylelint via stylefmt

This isn't true. stylefmt and stylelint are separate tools, although stylefmt can consume configs written for stylelint. There is already a grunt plugin for stylefmt: [grunt-stylefmt](https://github.com/morishitter/grunt-cssfmt). So that's already available to the community, and anyone wanting to format their CSS can use it in their grunt pipeline :)

**Comment by radum** [comment]
@jdforrester stylefmt is a separate tool and there is already a grunt plugin for it (grunt-stylefmt). Not sure if this will make sense to add here.

**Comment by jdforrester** [comment]
Sorry, I was paraphrasing http://stylelint.io/ 

Not adding it here will be immensely irritating; we'll just sub-duct it.

**Comment by ntwb** [comment]
FYI: The next release of stylelint will include experimental autofixing

**Comment by edg2s** [comment]
We pass through all config options, so setting 'fix' to true works as expected now.
